apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
  labels:
    app: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
        - name: cloud
          image: shivam184/cloud:0.0.5
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]